name: Scratch reusable

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo before
      - parallel:
          - name: One
            run: sleep 5 && echo one
          - name: Two
            run: sleep 5 && echo two
      - run: echo after
